[pins]
UP     = 4
DOWN   = 17
LEFT   = 27
RIGHT  = 22
A      = 25
B      = 24
X      = 15
Y      = 18
LL     = 14
RR     = 23
SELECT = 9
START  = 10
HK     = 16

[behavior]
debounce_ms = 30
repeat_delay_ms    = 400
repeat_interval_ms = 90
